# Test & Build
name: Test & Build

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  TestingCode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go (go1.17)
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup Go (go1.18beta2)
        run: |
          go install golang.org/dl/go1.18beta2@latest
          go1.18beta2 download

      - name: Run Tests
        run: make test

      - name: "Coverage: Install GoVeralls"
        env: { GO111MODULE: "off" }
        run: go get github.com/mattn/goveralls

      - name: "Coverage: Sending Report to coveralls.io"
        env:
          COVERALLS_TOKEN: ${{ secrets.github_token }}
        run: goveralls -coverprofile=coverage.out -service=github
